Use gitignore without flipping the meaning

diff --git a/lib/extras/git/git-functions b/lib/extras/git/git-functions
--- a/lib/extras/git/git-functions
+++ b/lib/extras/git/git-functions
@@ -1,5 +1,12 @@
 # git functions
 
+# Just some local things Mike uses (release early, release often)
+#
+# Worth a look:
+#
+# - git-repos: List all git repos (remote_url and git_dir)
+# - git-tarball-create: Creates a tarball based on a pecial gitignore file
+
 git-repos() {
 
     local search_dir="${1:-.}" # Use provided directory or default to current directory if not provided
@@ -15,6 +22,78 @@ git-repos() {
     | sort -k1,1 \
     | bma columnise
 }
+
+git-ls-noticed() {
+
+    # git-ls-included - List files from git index that not ignored by specified gitignore file.
+    #
+    # Usage: git-ls-noticed <gitignore_file>
+
+    local gitignore_file="${1:-}"
+
+    if [[ -z $gitignore_file ]]; then
+        echo "Usage: git-ls-included <gitignore_file>" >&2
+        return 1
+    elif [[ ! -f $gitignore_file ]]; then
+        echo "Error: File '$gitignore_file' not found." >&2
+        return 1
+    fi
+    gitignore_file="$(realpath "$gitignore_file")"
+    local git_repo_path="$(git rev-parse --show-toplevel)"
+
+    (
+        cd "${git_repo_path}" || exit
+        # Use git to list files for inclusion in the tarball
+        git ls-files --exclude-from="$gitignore_file"
+          # --cached # include uncommitted changes from git staging are
+          # --others # include untracked files
+    )
+}
+
+git-tarball-create() {
+
+    # git-tarball-create - Creates a tarball based on a single gitignore file
+    #
+    # Usage: git-tarball-create <gitignore_file>
+    #
+
+    local gitignore="${1:-}"
+
+    # Verify gitignore_file argument is provided
+    if [[ -z $gitignore_file ]]; then
+        echo "Usage: tarball-create <gitignore_file>" >&2
+        return 1
+    elif [[ ! -f $gitignore_file ]]; then
+        # Verify gitignore_file file exists
+        echo "Error: gitignore_file file '$gitignore_file' not found." >&2
+        return 1
+    fi
+
+    local last_commit_date="$(git log -1 --format=%cd --date=format:%Y-%m-%d)"
+    local git_repo_path="$(git rev-parse --show-toplevel)"
+    local git_repo_name="${git_repo_path##*/}"
+    local variant="$(basename "${gitignore_file}")"
+    local release="${git_repo_name}-${variant}-${last_commit_date}"
+    local build_dir="build"
+    local tarball="${build_dir}/${release}.tar.gz"
+
+    (
+        cd "${git_repo_path}" || exit
+        # Ensure the build directory exists
+        mkdir -p "$build_dir" || { echo "Failed to create build directory: $build_dir" >&2; return 1; }
+
+        # Use git to list files for inclusion in the tarball
+        if ! git-ls-included "$gitignore_file" \
+        | tar --transform "s,^,${release}/," -czf "${tarball}" -T -
+        then 
+            echo "Error: Failed to create tarball." >&2
+            return 1
+        fi
+    )
+
+    echo "Tarball created: ${tarball}"
+}
+
 
 git-repo-dirs(){
 
@@ -37,81 +116,46 @@ git-repos-save() {
 }
 
 git-repo-create() {
-    local repo_name=$1
-    git clone --bare $repo_name $repo_name.git
-    scp -r $repo_name.git git:git
-}
+    local repo_name=$(basename "$1" .git) # Ensures repo_name is derived cleanly
 
-git-ls-ignored() {
-
-    # git-ls-ignored - List files ignored by ignorefile
-    #
-    # Usage: git-ls-ignored <gitignore>
-    #
-    # If no gitignore file is provided, it fails
-
-    local gitignore="${1:-}"
-
-    if [[ -z $gitignore ]]; then
-        echo "Usage: git-ls-ignored <gitignore>" >&2
-        return 1
-    elif [[ ! -f $gitignore ]]; then
-        echo "Error: File '$gitignore' not found." >&2
-        return 1
-    fi
-    gitignore="$(realpath "$gitignore")"
-    local git_repo_path="$(git rev-parse --show-toplevel)"
-
-    (
-        cd "${git_repo_path}" || exit
-        # Use git to list files for inclusion in the tarball
-        git ls-files --ignored --exclude-from="$gitignore" --others --cached
-
-    )
-}
-
-git-tarball-create() {
-
-    # git-tarball-create - Creates a tarball based on a gitinclude file
-    #
-    # Usage: git-tarball-create <gitinclude>
-    #
-    # If no gitinclude file is provided, it prompts user to confirm they want everything.
-    # gitinclude is gitignore style file listing files and directories to include in the tarball.
-
-    local gitinclude="${1:-}"
-
-    # Verify gitinclude argument is provided
-    if [[ -z $gitinclude ]]; then
-        echo "Usage: tarball-create <gitinclude_path>" >&2
-        return 1
-    elif [[ ! -f $gitinclude ]]; then
-        # Verify .gitinclude file exists
-        echo "Error: Include file '$gitinclude' not found." >&2
+    # Prevent cloning into the same repository directory
+    if [ -d "$repo_name.git" ]; then
+        echo "A directory named '$repo_name.git' already exists. Exiting to avoid conflict."
         return 1
     fi
 
-    local last_commit_date="$(git log -1 --format=%cd --date=format:%Y-%m-%d)"
-    local git_repo_path="$(git rev-parse --show-toplevel)"
-    local git_repo_name="${git_repo_path##*/}"
-    local variant="$(basename "${gitinclude}")"
-    local release="${git_repo_name}-${variant}-${last_commit_date}"
-    local build_dir="build"
-    local tarball="${build_dir}/${release}.tar.gz"
-
+    # Ensure all files are committed in $repo_name
     (
-        cd "${git_repo_path}" || exit
-        # Ensure the build directory exists
-        mkdir -p "$build_dir" || { echo "Failed to create build directory: $build_dir" >&2; return 1; }
-
-        # Use git to list files for inclusion in the tarball
-        if ! git-ls-ignored "$gitinclude" \
-        | tar --transform "s,^,${release}/," -czfv "${tarball}" -T -
-        then 
-            echo "Error: Failed to create tarball." >&2
+        cd "$repo_name" || return 1
+        if ! git diff --quiet; then
+            echo "Uncommitted changes found in '$repo_name'. Please commit all changes before proceeding."
             return 1
         fi
     )
 
-    echo "Tarball created: ${tarball}"
+    # Clone as bare repository
+    if ! git clone --bare "$1" "$repo_name.git"; then
+        echo "Cloning failed. Please check the repository path."
+        return 1
+    fi
+
+    # Secure copy to remote server
+    if ! scp -r "$repo_name.git" git:git; then
+        echo "Failed to copy repository to remote server."
+        return 1
+    fi
+
+    # clone it
+    git clone "git.failmode.com_m:git/${repo_name}" "${repo_name}.cloned-from-remote"
+
+    # Move old repo
+    mv "${repo_name}" "${repo_name}.cloned_to_remote"
+
+    # Move new repo
+    mv "${repo_name}.cloned-from-remote" "${repo_name}"
+
+    echo "Repository '$repo_name.git' successfully cloned, copied to remote server and cloned back."
 }
+
+
+
