Add functions:
- cert-resource-record-valid: Check DNS domain validation record
- iam-access-key-rotate: rotate key
- ssm-automation-step-executions: list them

diff --git a/lib/extras/git/git-functions b/lib/extras/git/git-functions
--- a/lib/extras/git/git-functions
+++ b/lib/extras/git/git-functions
@@ -8,20 +8,106 @@
 # - git-tarball-create: Creates a tarball based on a gitinclude (special gitginore) file
 # - git-repos: List all git repos (remote_url and git_dir)
 
+git-tarball-create() {
+
+    # git-tarball-create - Creates a tarball based on a single gitinclude file
+    #
+    # Usage: git-tarball-create <gitinclude_file>
+    #
+
+    local gitinclude_file="${1:-}"
+
+    # Verify gitinclude_file argument is provided
+    if [[ -z $gitinclude_file ]]; then
+        echo "Usage: tarball-create <gitinclude_file>" >&2
+        return 1
+    elif [[ ! -f $gitinclude_file ]]; then
+        # Verify gitinclude_file file exists
+        echo "Error: gitinclude file '$gitinclude_file' not found." >&2
+        return 1
+    fi
+
+    local last_commit_date="$(git log -1 --format=%cd --date=format:%Y-%m-%d)"
+    local git_repo_path="$(git rev-parse --show-toplevel)"
+    local git_repo_name="${git_repo_path##*/}"
+    local variant="$(basename "${gitinclude_file}")"
+    local release="${git_repo_name}-${variant}-${last_commit_date}"
+    local build_dir="${git_repo_path}/build"
+    local tarball="${build_dir}/${release}.tar.gz"
+
+    (
+        cd "${git_repo_path}" || exit
+        # Ensure the build directory exists
+        mkdir -p "$build_dir" || { echo "Failed to create build directory: $build_dir" >&2; return 1; }
+
+        # Use git to list files for inclusion in the tarball
+        if ! git-ls-noticed "$gitinclude_file" \
+        | tar \
+            --transform "s,^,${release}/," \
+            --transform 's,${release}/\([^/]*\) -> \(.*\),\1 -> \2,' \
+            -czf "${tarball}" -T -
+        then 
+            echo "Error: Failed to create tarball." >&2
+            return 1
+        fi
+    )
+
+    echo "Tarball created: ${tarball}"
+}
+
+git-archive() {
+
+    local last_commit_date="$(git log -1 --format=%cd --date=format:%Y-%m-%d)"
+    local git_repo_path="$(git rev-parse --show-toplevel)"
+    local git_repo_name="${git_repo_path##*/}"
+    local release="${git_repo_name}-${last_commit_date}"
+    local build_dir="${git_repo_path}/build"
+    local tarball="${build_dir}/${release}.tar.gz"
+    local label="$(basename $(git rev-parse --show-toplevel))-$(git log -1 --format=%cd --date=format:%Y-%m-%d)"
+
+    (
+        cd "${git_repo_path}" || exit
+
+        # Ensure the build directory exists
+        mkdir -p "$build_dir" || { echo "Failed to create build directory: $build_dir" >&2; return 1; }
+
+        git archive \
+        --prefix="${release}/"  \
+        --format=tar.gz      \
+        -o "${build_dir}/${release}.tar.gz" \
+        HEAD
+    )
+}
+
+git-remote-add-github() {
+    git remote add github "github.com_mbailey:mbailey/$(git-repo-name).git"
+    git branch -M master
+    git push -u github master
+}
+
+git-repo-name() {
+  basename "$(git rev-parse --show-toplevel)"
+}
+
 git-repos() {
 
-    local search_dir="${1:-.}" # Use provided directory or default to current directory if not provided
+    local search_dirs="$(skim-stdin "$@")"
+    [[ -z $search_dirs ]] && search_dirs='.'
+    
+    # debug "$search_dirs"
 
-    # Find all .git directories under the specified directory
-    find "$search_dir" -type d -name .git 2>/dev/null | while read -r git_dir; do
-        local repo_dir
-        repo_dir=$(dirname "$git_dir") # Get the repository directory by removing the .git part
-        local repo_url
-        repo_url=$(git -C "$repo_dir" config --get remote.origin.url) # Get the repository's remote URL
-        printf "%s\t%s\n" "$repo_url" "${repo_dir}" # Print the repository URL and directory path, separated by a tab
-    done \
-    | sort -k1,1 \
-    | bma columnise
+    # Find all .git directories under the specified directories
+    for search_dir in $search_dirs; do
+        find -L "$search_dir" -type d -name .git 2>/dev/null | while read -r git_dir; do
+            local repo_dir
+            repo_dir=$(dirname "$git_dir") # Get the repository directory by removing the .git part
+            local repo_url
+            repo_url=$(git -C "$repo_dir" config --get remote.origin.url) # Get the repository's remote URL
+            printf "%s\t%s\n" "$repo_url" "${repo_dir}" # Print the repository URL and directory path, separated by a tab
+        done \
+        | sort -k1,1 \
+        | bma columnise
+    done
 }
 
 git-ls-noticed() {
@@ -36,6 +122,10 @@ git-ls-noticed() {
     #     `--ignored`: Lists all files that are ignored by git
     #     `--cached`: Lists all files that are staged for commit. (Required to use `--ignored`.)
     #     `--exclude-from`: Use specified file as the ignore file (and ignore all others)
+    #
+    # Test with:
+    #
+    # diff <(git-ls-noticed path/to/.gitinclude/target)  <(tar-ls build/example-target-2024-04-17.tar.gz)
 
     local gitinclude_file="${1:-}"
 
@@ -65,49 +155,6 @@ git-ls-noticed() {
     )
 }
 
-git-tarball-create() {
-
-    # git-tarball-create - Creates a tarball based on a single gitinclude file
-    #
-    # Usage: git-tarball-create <gitinclude_file>
-    #
-
-    local gitinclude_file="${1:-}"
-
-    # Verify gitinclude_file argument is provided
-    if [[ -z $gitinclude_file ]]; then
-        echo "Usage: tarball-create <gitinclude_file>" >&2
-        return 1
-    elif [[ ! -f $gitinclude_file ]]; then
-        # Verify gitinclude_file file exists
-        echo "Error: gitinclude file '$gitinclude_file' not found." >&2
-        return 1
-    fi
-
-    local last_commit_date="$(git log -1 --format=%cd --date=format:%Y-%m-%d)"
-    local git_repo_path="$(git rev-parse --show-toplevel)"
-    local git_repo_name="${git_repo_path##*/}"
-    local variant="$(basename "${gitinclude_file}")"
-    local release="${git_repo_name}-${variant}-${last_commit_date}"
-    local build_dir="build"
-    local tarball="${build_dir}/${release}.tar.gz"
-
-    (
-        cd "${git_repo_path}" || exit
-        # Ensure the build directory exists
-        mkdir -p "$build_dir" || { echo "Failed to create build directory: $build_dir" >&2; return 1; }
-
-        # Use git to list files for inclusion in the tarball
-        if ! git-ls-noticed "$gitinclude_file" \
-        | tar --transform "s,^,${release}/," -czf "${tarball}" -T -
-        then 
-            echo "Error: Failed to create tarball." >&2
-            return 1
-        fi
-    )
-
-    echo "Tarball created: ${tarball}"
-}
 
 
 git-repo-dirs(){
