Revert accidental commit to aws-account-each()
Is anyone using this command? It requires setup of an assumable role
in each account. Not bad but a bit of setup required.

diff --git a/lib/aws-account-functions b/lib/aws-account-functions
--- a/lib/aws-account-functions
+++ b/lib/aws-account-functions
@@ -85,24 +85,21 @@ aws-account-each() {
 
   local aws_account_ids=$(skim-stdin)
   local cmd=$@
-  local assumed_role_name="${AWS_PANOPTICON_ROLE_NAME:-admin}"
+  local assumed_role_name="${AWS_PANOPTICON_ROLE_NAME:-SecurityAuditor}"
   [[ -z $aws_account_ids ]] && __bma_usage "cmd # pipe in AWS_ACCOUNT_IDS" && return 1
 
   echo "#command=${cmd}"
   echo "#"
 
   for aws_account_id in $aws_account_ids; do
-    bob awslogin $aws_account_id
-    $cmd
-
-    # local assumed_env=$(sts-assume-role "arn:aws:iam::${aws_account_id}:role/${assumed_role_name}")
-    # [[ -z "$assumed_env" ]] && continue # AWSCLI prints error if assuming role fails
-    # local aws_account_alias="$(export $assumed_env && aws-account-alias)"
-    # echo "#account=$aws_account_id alias=${aws_account_alias}"
-    # if ! output=$(export $assumed_env && eval "$cmd"); then
-    #   : # something went wrong
-    # fi
-    # [ -z "$output" ] || printf '%s\n\n' "${output%$'\n'}"
+    local assumed_env=$(sts-assume-role "arn:aws:iam::${aws_account_id}:role/${assumed_role_name}")
+    [[ -z "$assumed_env" ]] && continue # AWSCLI prints error if assuming role fails
+    local aws_account_alias="$(export $assumed_env && aws-account-alias)"
+    echo "#account=$aws_account_id alias=${aws_account_alias}"
+    if ! output=$(export $assumed_env && eval "$cmd"); then
+      : # something went wrong
+    fi
+    [ -z "$output" ] || printf '%s\n\n' "${output%$'\n'}"
   done
 }
 
