aws-panopticon() runs commands across multiple accounts

diff --git a/lib/misc-functions b/lib/misc-functions
--- a/lib/misc-functions
+++ b/lib/misc-functions
@@ -2,6 +2,33 @@
 #
 # miscellaneous functions that don't belong anywhere else
 
+
+# aws-panopticon - Run command on multiple AWS Accounts
+#
+# Reads AWS Account IDs from STDIN
+# Assumes an IAM Role on each account and runs command given as arguments
+#
+aws-panopticon() {
+  local aws_account_ids="$(__bma_read_inputs)"
+  local cmd=$@
+  local assumed_role_name="${AWS_PANOPTICON_ROLE_NAME:-Auditor}"
+  [[ -z "${aws_account_ids}" ]] && __bma_usage "cmd # pipe in AWS_ACCOUNT_IDS" && return 1
+
+  echo "#command=${cmd}"
+  echo "#"
+
+  for aws_account_id in $aws_account_ids; do
+    local assumed_env=$(sts-assume-role "arn:aws:iam::${aws_account_id}:role/${assumed_role_name}")
+    [[ -z "$assumed_env" ]] && continue # AWSCLI prints error if assuming role fails
+    local aws_account_alias="$(eval $assumed_env aws-account-alias)"
+    echo "#account=$aws_account_id alias=${aws_account_alias}"
+    if ! output="$(eval $assumed_env $cmd)"; then
+      : # something went wrong
+    fi
+    [ -z "$output" ] || printf '%s\n\n' "${output%$'\n'}"
+  done
+}
+
 regions() {
   aws ec2 describe-regions           \
     --query "Regions[].[RegionName]" \
@@ -31,3 +58,4 @@ aws-account-alias() {
     --query AccountAliases     \
     --output text
 }
+
