Revert "Validate stack-failure inputs"
This reverts commit 808cc3bab012e4f3b20795bb0ace816012f5f92d.

diff --git a/lib/stack-functions b/lib/stack-functions
--- a/lib/stack-functions
+++ b/lib/stack-functions
@@ -154,8 +154,12 @@ stack-delete() {
 }
 
 stack-failure() {
-  [[ -z $1 ]] && __bma_usage "[stack]" || return 1
-  local stack=$1
+  # FIXME: only grab the latest failure
+  local inputs=$(__bma_read_inputs $@)
+  local first_resource=$(__bma_read_resources ${inputs} | awk '{print $1}')
+  local stack=$(_stack_name_arg $first_resource)
+
+  if [[ -z ${stack} ]]; then __bma_error "Usage: $FUNCNAME stack" || return 1; fi
 
   local query='
     StackEvents[?contains(ResourceStatus,`FAILED`)].[
